# Generated by Django 5.1.7 on 2025-04-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tokens_mercado_livre_correto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filial', models.TextField()),
                ('refresh_token', models.CharField(max_length=250)),
                ('access_token', models.CharField(max_length=250)),
            ],
        ),
    ]
